dependencies:
- name: pipeline-cluster-monitor
  repository: https://kubernetes-charts.banzaicloud.com
  version: '>=0.1.17'
  alias: pipeline-monitor
  condition: pipeline-monitor.enabled
- name: pipeline-cluster-ingress
  repository: https://kubernetes-charts.banzaicloud.com
  version: '>=0.0.8'
  alias: pipeline-ingress
  condition: pipeline-ingress.enabled
- name: postgresql
  repository: "file://../postgresql"
  version: 5.0.0
  alias: postgresql
  condition: postgresql.enabled
- name: redis
  repository: "file://../redis"
  version: 8.0.18
  alias: redis
  condition: redis.enabled